name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:
 
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup .NET
      uses: actions/setup-dotnet@v2
      with:
        dotnet-version: 6.0.x
    - name: Restore dependencies
      run: dotnet restore Restaurant Reviews Projects/RestaurantApp/RestaurantApi
    - name: Build
      run: dotnet build --no-restore Restaurant Reviews Projects/RestaurantApp/RestaurantApi
    - name: Test
      run: dotnet test --no-build --verbosity normal Restaurant Reviews Projects/RestaurantApp/RestaurantApi
